{
  "uid" : "5312127cbee28bee",
  "name" : "test 04.02.01 create an account with correct data",
  "fullName" : "tests.test_create_an_account.TestCreateAnAccount#test_tc_04_02_01_create_account_with_correct_data",
  "historyId" : "5ae4b645f46800dae8c6eb0e3f056903",
  "time" : {
    "start" : 1688258328445,
    "stop" : 1688258328445,
    "duration" : 0
  },
  "description" : " Verify that customer can Create An Account with correct data",
  "descriptionHtml" : "<p>Verify that customer can Create An Account with correct data</p>\n",
  "status" : "skipped",
  "statusMessage" : "Skipped: customer will Create An Account with correct data",
  "statusTrace" : "('/home/runner/work/luma_project/luma_project/tests/test_create_an_account.py', 164, 'Skipped: customer will Create An Account with correct data')",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_result_folder",
    "time" : {
      "start" : 1688258315828,
      "stop" : 1688258315828,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1688258328447,
      "stop" : 1688258329090,
      "duration" : 643
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5574757ef4e3 <unknown>\n#1 0x55747551ec76 <unknown>\n#2 0x557475547d78 <unknown>\n#3 0x557475544029 <unknown>\n#4 0x557475582ccc <unknown>\n#5 0x55747558247f <unknown>\n#6 0x557475579de3 <unknown>\n#7 0x55747554f2dd <unknown>\n#8 0x55747555034e <unknown>\n#9 0x5574757af3e4 <unknown>\n#10 0x5574757b33d7 <unknown>\n#11 0x5574757bdb20 <unknown>\n#12 0x5574757b4023 <unknown>\n#13 0x5574757821aa <unknown>\n#14 0x5574757d86b8 <unknown>\n#15 0x5574757d8847 <unknown>\n#16 0x5574757e8243 <unknown>\n#17 0x7f04fcd17b43 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/conftest.py\", line 24, in driver\n    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1688258315743,
      "stop" : 1688258315828,
      "duration" : 85
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "clear_allure_result_folder::0",
    "time" : {
      "start" : 1688258597329,
      "stop" : 1688258597329,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Create An Account"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.skip(reason='customer will Create An Account with correct data')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_create_an_account"
  }, {
    "name" : "subSuite",
    "value" : "TestCreateAnAccount"
  }, {
    "name" : "host",
    "value" : "fv-az1025-316"
  }, {
    "name" : "thread",
    "value" : "2308-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_create_an_account"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.skip(reason='customer will Create An Account with correct data')" ]
  },
  "source" : "5312127cbee28bee.json",
  "parameterValues" : [ ]
}