{
  "uid" : "5d43fc0d87c05373",
  "name" : "test 04.02.01 create an account with correct data",
  "fullName" : "tests.test_create_an_account.TestCreateAnAccount#test_tc_04_02_01_create_account_with_correct_data",
  "historyId" : "5ae4b645f46800dae8c6eb0e3f056903",
  "time" : {
    "start" : 1688333690214,
    "stop" : 1688333690214,
    "duration" : 0
  },
  "description" : " Verify that customer can Create An Account with correct data",
  "descriptionHtml" : "<p>Verify that customer can Create An Account with correct data</p>\n",
  "status" : "skipped",
  "statusMessage" : "Skipped: customer will Create An Account with correct data",
  "statusTrace" : "('/home/runner/work/luma_project/luma_project/tests/test_create_an_account.py', 179, 'Skipped: customer will Create An Account with correct data')",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1688333675712,
      "stop" : 1688333675804,
      "duration" : 92
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1688333690216,
      "stop" : 1688333690864,
      "duration" : 648
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x559d3807c4e3 <unknown>\n#1 0x559d37dabc76 <unknown>\n#2 0x559d37dd4d78 <unknown>\n#3 0x559d37dd1029 <unknown>\n#4 0x559d37e0fccc <unknown>\n#5 0x559d37e0f47f <unknown>\n#6 0x559d37e06de3 <unknown>\n#7 0x559d37ddc2dd <unknown>\n#8 0x559d37ddd34e <unknown>\n#9 0x559d3803c3e4 <unknown>\n#10 0x559d380403d7 <unknown>\n#11 0x559d3804ab20 <unknown>\n#12 0x559d38041023 <unknown>\n#13 0x559d3800f1aa <unknown>\n#14 0x559d380656b8 <unknown>\n#15 0x559d38065847 <unknown>\n#16 0x559d38075243 <unknown>\n#17 0x7f4eef54fb43 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/conftest.py\", line 25, in driver\n    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  }, {
    "name" : "clear_allure_result_folder",
    "time" : {
      "start" : 1688333675804,
      "stop" : 1688333675804,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "clear_allure_result_folder::0",
    "time" : {
      "start" : 1688333966703,
      "stop" : 1688333966703,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Create An Account"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.skip(reason='customer will Create An Account with correct data')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_create_an_account"
  }, {
    "name" : "subSuite",
    "value" : "TestCreateAnAccount"
  }, {
    "name" : "host",
    "value" : "fv-az1236-176"
  }, {
    "name" : "thread",
    "value" : "2322-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_create_an_account"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.skip(reason='customer will Create An Account with correct data')" ]
  },
  "source" : "5d43fc0d87c05373.json",
  "parameterValues" : [ ]
}