{
  "uid" : "80aa7991fbc4a108",
  "name" : "TC 03.02.01 to 03_02_10 Verify and Failed Login, no error validation",
  "fullName" : "tests.test_sign_in.TestFailedLogin#test_03_02_01_to_03_02_10_login",
  "historyId" : "0029e97b34628286aac0dce42d8b2f6a",
  "time" : {
    "start" : 1688258578763,
    "stop" : 1688258578763,
    "duration" : 0
  },
  "description" : "Check Success and Failed Login, no error validation",
  "descriptionHtml" : "<p>Check Success and Failed Login, no error validation</p>\n",
  "status" : "skipped",
  "statusMessage" : "Skipped: to be run with secret code for captcha",
  "statusTrace" : "('/home/runner/work/luma_project/luma_project/tests/test_sign_in.py', 250, 'Skipped: to be run with secret code for captcha')",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_result_folder",
    "time" : {
      "start" : 1688258315828,
      "stop" : 1688258315828,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1688258578779,
      "stop" : 1688258579422,
      "duration" : 643
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5593944c14e3 <unknown>\n#1 0x5593941f0c76 <unknown>\n#2 0x559394219d78 <unknown>\n#3 0x559394216029 <unknown>\n#4 0x559394254ccc <unknown>\n#5 0x55939425447f <unknown>\n#6 0x55939424bde3 <unknown>\n#7 0x5593942212dd <unknown>\n#8 0x55939422234e <unknown>\n#9 0x5593944813e4 <unknown>\n#10 0x5593944853d7 <unknown>\n#11 0x55939448fb20 <unknown>\n#12 0x559394486023 <unknown>\n#13 0x5593944541aa <unknown>\n#14 0x5593944aa6b8 <unknown>\n#15 0x5593944aa847 <unknown>\n#16 0x5593944ba243 <unknown>\n#17 0x7f70dcc9cb43 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/conftest.py\", line 24, in driver\n    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1688258315743,
      "stop" : 1688258315828,
      "duration" : 85
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "clear_allure_result_folder::0",
    "time" : {
      "start" : 1688258597329,
      "stop" : 1688258597329,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Login Functionality with captcha"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(raises=<class 'AssertionError'>)"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.skip(reason='to be run with secret code for captcha')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_sign_in"
  }, {
    "name" : "subSuite",
    "value" : "TestFailedLogin"
  }, {
    "name" : "host",
    "value" : "fv-az1025-316"
  }, {
    "name" : "thread",
    "value" : "2308-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_sign_in"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "email",
    "value" : "''"
  }, {
    "name" : "password",
    "value" : "'Test#12p@ssword'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.skip(reason='to be run with secret code for captcha')", "@pytest.mark.xfail(raises=<class 'AssertionError'>)" ]
  },
  "source" : "80aa7991fbc4a108.json",
  "parameterValues" : [ "''", "'Test#12p@ssword'" ]
}